apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: test-mvp-component-vwfk
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - env:
        - name: var_name
          value: test
        image: quay.io/redhat-appstudio-qe/test-images@sha256:40de0391b85912efb1741968fe44e552000a1016f6424427034ff07700a5d624
        name: hacbs-jvm-build-test-project
        resources: {}
status: {}
